# _config.yml
title: "我的精品文章展示站"
description: "精选技术文章与思考"
baseurl: "" 
url: "https://你的用户名.github.io"

# 主题设置
theme: minima

# 作者信息
author:
  name: "您的名字"
  email: "您的邮箱"

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 构建设置
markdown: kramdown
permalink: pretty

# 禁用评论
comments: false

# 社交媒体链接（可选）
github_username: 您的GitHub用户名

# 自定义变量
show_excerpts: true
future: false

initial Jekyll config
