# _config.yml
title: "我的精品文章展示站"
description: "精选技术文章与思考"
baseurl: "" 
url: "https://zhuiyuxingchen.github.io"

# 主题设置
theme: jekyll-theme-cayman

# 作者信息
author:
  name: "zhuiyuxingchen"

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 构建设置
markdown: kramdown
permalink: pretty

# 禁用评论
comments: false

# 社交媒体链接（可选）
github_username: zhuiyuxingchen

# 自定义变量
show_excerpts: true
future: false

# 添加到 _config.yml 中
header_pages:
  - about.md
  - archives.md
# 如果你的主题支持，这会自动在顶部导航生成链接
# 在 _config.yml 中添加：
header_pages:
  - index.md
  - archives.md    # 作为"分类"页面
  - tags.md        # 标签页面
  - about.md       # 可以作为"登录"或"关于"
